name: workers_dart_example
description: A sample Cloudflare worker written in Dart.
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  fetch_apis: 0.0.1
  cloudflare_workers: 0.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
