name = "dart-worker-example"
compatibility_date = "2022-11-30"
main = ".dart_tool/worker/main.dart.js"

[build]
command = "dart compile js --server-mode -O4 -o .dart_tool/worker/main.dart.js lib/main.dart"
watch_dir = "lib"
