name = "dart-worker-example"
compatibility_date = "2022-11-30"
main = ".dart_tool/worker/main.dart.js"

[build]
# add -O4 to enable dart2js optimizations in prod
# Note: --no-frequency-based-minification is required for server mode, 
# otherwise typerrors; TypeError: Instance of 'minified:u<minified:N>': type 'minified:u<minified:N>' is not a subtype of type 'minified:u<dynamic>'
# Prod:
command = "dart compile js -O4 --no-frequency-based-minification --server-mode -o .dart_tool/worker/main.dart.js lib/main.dart"
# Local:
# command = "dart compile js  --no-frequency-based-minification --server-mode -o .dart_tool/worker/main.dart.js lib/main.dart"
watch_dir = ["../packages", "lib"]
