name: edge_example
description: A basic example of using the edge package.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/edge
version: 0.0.2

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.2
