name: cloudflare_workers

repository: https://github.com/invertase/dart_workers

packages:
  - packages/**
  - example

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

ide:
  intellij: true
