name: netlify_edge
version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: 0.0.1
  js_bindings:
    git:
      url: https://github.com/jodinathan/js_bindings.git
      ref: b1e53c4a3d7e488e39e290044554493fc9b26576
  js: ^0.6.5
  path: ^1.8.3
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
