name: cloudflare_workers
description: Write and deploy Dart functions to Cloudflare Workers.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/cloudflare_workers
version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: 0.0.1
  js_bindings:
    git:
      url: https://github.com/jodinathan/js_bindings.git
      ref: b1e53c4a3d7e488e39e290044554493fc9b26576
  js: ^0.6.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
