name = "example-js"
main = "src/index.ts"
compatibility_date = "2023-01-23"

[durable_objects]
bindings = [
  { name = "EXAMPLE_CLASS", class_name = "DurableObjectExample" } # Binding to our DurableObjectExample class
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["DurableObjectExample"]