name: edge
description: An Vercel Edge function written in Dart.
homepage: https://dartedge.dev
repository: https://github.com/invertase/dart_edge/tree/main/packages/edge
version: 0.0.2

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  js: ^0.6.5
  js_bindings: ^0.1.0
  args: ^2.3.2
  cli_util: ^0.3.5
  path: ^1.8.3
  hotreloader: ^3.0.5
  toml: ^0.13.1
  mason: ^0.1.0-dev.41
  watcher: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
