name: edge
description: TODO
repository: https://github.com/invertase/dart_edge
version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies: 
  args: ^2.3.2
  cli_util: ^0.3.5
  path: ^1.8.3
  watcher: ^1.0.2
  toml: ^0.13.1
  typed_data: ^1.3.1

executables:
  edge: