name: edge
description: TODO
repository: https://github.com/invertase/dart_edge
version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  args: ^2.3.2
  cli_util: ^0.3.5
  path: ^1.8.3
  watcher: ^1.0.2
  toml: ^0.13.1
  freezed_annotation: ^2.2.0
  js_bindings:
    git:
      url: https://github.com/jodinathan/js_bindings.git
      ref: b1e53c4a3d7e488e39e290044554493fc9b26576
  js: ^0.6.5

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3

executables:
  edge:
