name: cloudflare_workers_example
description: An example Cloudflare Worker written in Dart.
version: 1.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloudflare_workers: 0.0.1
  edge: ^0.0.1
