name: v8_runtime
version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  js_bindings: ^0.0.10
  js: ^0.6.5

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
